// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt32, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
		{Name: "capacity", Type: field.TypeInt16},
		{Name: "description", Type: field.TypeString, Default: "unknown"},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// EventsUsersColumns holds the columns for the "events_users" table.
	EventsUsersColumns = []*schema.Column{
		{Name: "events_id", Type: field.TypeInt32},
		{Name: "user_id", Type: field.TypeInt},
	}
	// EventsUsersTable holds the schema information for the "events_users" table.
	EventsUsersTable = &schema.Table{
		Name:       "events_users",
		Columns:    EventsUsersColumns,
		PrimaryKey: []*schema.Column{EventsUsersColumns[0], EventsUsersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "events_users_events_id",
				Columns:    []*schema.Column{EventsUsersColumns[0]},
				RefColumns: []*schema.Column{EventsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "events_users_user_id",
				Columns:    []*schema.Column{EventsUsersColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EventsTable,
		UsersTable,
		EventsUsersTable,
	}
)

func init() {
	EventsUsersTable.ForeignKeys[0].RefTable = EventsTable
	EventsUsersTable.ForeignKeys[1].RefTable = UsersTable
}
