// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dpolimeni/fiber_app/ent/events"
	"github.com/dpolimeni/fiber_app/ent/reservations"
	"github.com/dpolimeni/fiber_app/ent/user"
)

// ReservationsCreate is the builder for creating a Reservations entity.
type ReservationsCreate struct {
	config
	mutation *ReservationsMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (rc *ReservationsCreate) SetCreatedAt(t time.Time) *ReservationsCreate {
	rc.mutation.SetCreatedAt(t)
	return rc
}

// SetID sets the "id" field.
func (rc *ReservationsCreate) SetID(s string) *ReservationsCreate {
	rc.mutation.SetID(s)
	return rc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (rc *ReservationsCreate) SetUserID(id int) *ReservationsCreate {
	rc.mutation.SetUserID(id)
	return rc
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (rc *ReservationsCreate) SetNillableUserID(id *int) *ReservationsCreate {
	if id != nil {
		rc = rc.SetUserID(*id)
	}
	return rc
}

// SetUser sets the "user" edge to the User entity.
func (rc *ReservationsCreate) SetUser(u *User) *ReservationsCreate {
	return rc.SetUserID(u.ID)
}

// SetEventID sets the "event" edge to the Events entity by ID.
func (rc *ReservationsCreate) SetEventID(id int32) *ReservationsCreate {
	rc.mutation.SetEventID(id)
	return rc
}

// SetNillableEventID sets the "event" edge to the Events entity by ID if the given value is not nil.
func (rc *ReservationsCreate) SetNillableEventID(id *int32) *ReservationsCreate {
	if id != nil {
		rc = rc.SetEventID(*id)
	}
	return rc
}

// SetEvent sets the "event" edge to the Events entity.
func (rc *ReservationsCreate) SetEvent(e *Events) *ReservationsCreate {
	return rc.SetEventID(e.ID)
}

// Mutation returns the ReservationsMutation object of the builder.
func (rc *ReservationsCreate) Mutation() *ReservationsMutation {
	return rc.mutation
}

// Save creates the Reservations in the database.
func (rc *ReservationsCreate) Save(ctx context.Context) (*Reservations, error) {
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *ReservationsCreate) SaveX(ctx context.Context) *Reservations {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *ReservationsCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *ReservationsCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *ReservationsCreate) check() error {
	if _, ok := rc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Reservations.created_at"`)}
	}
	return nil
}

func (rc *ReservationsCreate) sqlSave(ctx context.Context) (*Reservations, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Reservations.ID type: %T", _spec.ID.Value)
		}
	}
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *ReservationsCreate) createSpec() (*Reservations, *sqlgraph.CreateSpec) {
	var (
		_node = &Reservations{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(reservations.Table, sqlgraph.NewFieldSpec(reservations.FieldID, field.TypeString))
	)
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rc.mutation.CreatedAt(); ok {
		_spec.SetField(reservations.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := rc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reservations.UserTable,
			Columns: []string{reservations.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_reservations = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reservations.EventTable,
			Columns: []string{reservations.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(events.FieldID, field.TypeInt32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.events_reservations = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ReservationsCreateBulk is the builder for creating many Reservations entities in bulk.
type ReservationsCreateBulk struct {
	config
	err      error
	builders []*ReservationsCreate
}

// Save creates the Reservations entities in the database.
func (rcb *ReservationsCreateBulk) Save(ctx context.Context) ([]*Reservations, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Reservations, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReservationsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *ReservationsCreateBulk) SaveX(ctx context.Context) []*Reservations {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *ReservationsCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *ReservationsCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
