-- Create "events" table
CREATE TABLE "events" ("id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL DEFAULT 'unknown', "capacity" smallint NOT NULL, "description" character varying NOT NULL DEFAULT 'unknown', PRIMARY KEY ("id"));
-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "age" bigint NOT NULL, "name" character varying NOT NULL DEFAULT 'unknown', PRIMARY KEY ("id"));
-- Create "events_users" table
CREATE TABLE "events_users" ("events_id" integer NOT NULL, "user_id" bigint NOT NULL, PRIMARY KEY ("events_id", "user_id"), CONSTRAINT "events_users_events_id" FOREIGN KEY ("events_id") REFERENCES "events" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "events_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "reservations" table
CREATE TABLE "reservations" ("id" character varying NOT NULL, "created_at" timestamptz NOT NULL, "events_reservations" integer NULL, "user_reservations" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "reservations_events_reservations" FOREIGN KEY ("events_reservations") REFERENCES "events" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "reservations_users_reservations" FOREIGN KEY ("user_reservations") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
